[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
voting_dapp = "EuKDEhzL4VSXHRQqDudWXwaorsR8yZxL3aZ3VS7rKp3w"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/soul/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
